name: 'Experiment #3 - Checkout, Branches, and Conditionals'

on:
  push:
    branches:
      - experimental

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v3
      - name: List the contents of the repository.
        run: |
          echo $PWD
          ls -R
          git rev-parse --abbrev-ref HEAD
          echo "github.ref: ${{ github.ref }}"
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print something random.
        run: |
          echo "Hello, Galaxy!"
          echo "github.ref: ${{ github.ref }}"
