name: 'Experiment #2 - Artifacts'

on: workflow_dispatch

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Create a plain text file.
        run: |
          echo 'Hello, world!' > hello.txt
      - name: List contents of the current working directory.
        run: |
          echo $PWD
          ls -R
      - name: Archive the artifact.
        uses: actions/upload-artifact@v3
        with:
          name: hello-txt
          path: ./hello.txt
